/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.awt.event.WindowListener;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

import controller.FrameInicialController;
import model.Curso;
import model.Usuario;

/**
 *
 * @author a1647890
 */
public class FrameInicial extends javax.swing.JFrame {

	/**
	 * Creates new form FrameInicial
	 */
	public FrameInicial() {
		initComponents();

		SwingUtilities.invokeLater(new Runnable() {

			@Override
			public void run() {
				FrameInicialController controller = new FrameInicialController();
				for (Usuario usuario : controller.getUsuarios()) {
					comboboxUsuario.addItem(usuario);
				}
			}
		});

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		mainPanel = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		botaoCarregarPrograma = new javax.swing.JButton();
		labelTitulo = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		comboboxUsuario = new javax.swing.JComboBox<>();
		jPanel1 = new javax.swing.JPanel();
		comboboxCurso = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(840, 600));
		setResizable(false);
		getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

		mainPanel.setMinimumSize(new java.awt.Dimension(840, 600));
		mainPanel.setPreferredSize(new java.awt.Dimension(840, 600));

		botaoCarregarPrograma.setText("Iniciar");
		botaoCarregarPrograma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoCarregarProgramaActionPerformed(evt);
			}
		});

		labelTitulo.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
		labelTitulo.setText("Lacroix");
		labelTitulo.setVerifyInputWhenFocusTarget(false);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));

		comboboxUsuario.setModel(new DefaultComboBoxModel<>());
		comboboxUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comboboxUsuarioActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout
						.createSequentialGroup().addGap(0, 0, 0).addComponent(comboboxUsuario,
								javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(0, 0, 0).addComponent(comboboxUsuario,
						javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)));

		jPanel3.add(jPanel2);

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));

		comboboxCurso.setModel(new DefaultComboBoxModel<>());
		comboboxCurso.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comboboxCursoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout
						.createSequentialGroup().addGap(0, 0, 0).addComponent(comboboxCurso,
								javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(0, 0, 0)
						.addComponent(comboboxCurso, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)));

		jPanel3.add(jPanel1);

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel4Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(botaoCarregarPrograma)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel4Layout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(labelTitulo)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap(31, Short.MAX_VALUE)
						.addComponent(labelTitulo).addGap(18, 18, Short.MAX_VALUE)
						.addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
						.addComponent(botaoCarregarPrograma).addContainerGap(21, Short.MAX_VALUE)));

		javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
		mainPanel.setLayout(mainPanelLayout);
		mainPanelLayout
				.setHorizontalGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		mainPanelLayout.setVerticalGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						mainPanelLayout.createSequentialGroup().addContainerGap(184, Short.MAX_VALUE)
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(183, 183, 183)));

		getContentPane().add(mainPanel);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void comboboxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboboxUsuarioActionPerformed
		SwingUtilities.invokeLater(new Runnable() {

			@Override
			public void run() {
				FrameInicialController controller = new FrameInicialController();
				if (comboboxUsuario.getSelectedIndex() != -1) {
					for (Curso curso : controller.getCursos((Usuario) comboboxUsuario.getSelectedItem())) {
						comboboxCurso.addItem(curso);
					}
					if (comboboxCurso.getItemCount() > 0) {
						comboboxCurso.setEnabled(true);
						botaoCarregarPrograma.setEnabled(true);
					}
				}
			}
		});
	}// GEN-LAST:event_comboboxUsuarioActionPerformed

	private void comboboxCursoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboboxCursoActionPerformed

	}// GEN-LAST:event_comboboxCursoActionPerformed

	private void botaoCarregarProgramaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCarregarProgramaActionPerformed

		this.dispose();
		ModeloMainFrame frame = new ModeloMainFrame((Usuario) comboboxUsuario.getSelectedItem(),
				(Curso) comboboxCurso.getSelectedItem());

		frame.setVisible(true);
		frame.setFocusableWindowState(true);

	}// GEN-LAST:event_botaoCarregarProgramaActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				FrameInicial frame = new FrameInicial();
				frame.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton botaoCarregarPrograma;
	private javax.swing.JComboBox<Curso> comboboxCurso;
	private javax.swing.JComboBox<Usuario> comboboxUsuario;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JLabel labelTitulo;
	private javax.swing.JPanel mainPanel;
	// End of variables declaration//GEN-END:variables
}
