/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;

import controller.FrameInicialController;
import model.Curso;
import model.Usuario;

/**
 *
 * @author a1647890
 */
public class FrameInicial extends javax.swing.JFrame {

	/**
	 * Creates new form FrameInicial
	 */
	public FrameInicial() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		mainPanel = new javax.swing.JPanel();
		labelTitulo = new javax.swing.JLabel();
		labelUsuario = new javax.swing.JLabel();
		comboboxUsuario = new javax.swing.JComboBox<>();
		labelCurso = new javax.swing.JLabel();
		comboboxCurso = new javax.swing.JComboBox<>();
		botaoCarregarPrograma = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setMinimumSize(new java.awt.Dimension(820, 570));
		getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

		mainPanel.setLayout(new java.awt.GridBagLayout());

		labelTitulo.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
		labelTitulo.setText("Lacroix");
		labelTitulo.setVerifyInputWhenFocusTarget(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 18, 0);
		mainPanel.add(labelTitulo, gridBagConstraints);

		labelUsuario.setText("Usuário");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		mainPanel.add(labelUsuario, gridBagConstraints);
		comboboxUsuario.setModel(new javax.swing.DefaultComboBoxModel<>());

		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				FrameInicialController controller = new FrameInicialController();
				for (Usuario usuario : controller.getUsuarios()) {
					comboboxUsuario.addItem(usuario);
				}
				comboboxUsuario.setSelectedIndex(-1);
			}
		});

		comboboxUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comboboxUsuarioActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		mainPanel.add(comboboxUsuario, gridBagConstraints);

		labelCurso.setText("Curso");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		mainPanel.add(labelCurso, gridBagConstraints);

		comboboxCurso.setEnabled(false);
		comboboxCurso.setModel(new javax.swing.DefaultComboBoxModel<>());
		comboboxCurso.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comboboxCursoActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		mainPanel.add(comboboxCurso, gridBagConstraints);

		botaoCarregarPrograma.setText("Iniciar");
		botaoCarregarPrograma.setEnabled(false);
		botaoCarregarPrograma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoCarregarProgramaActionPerformed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
		gridBagConstraints.insets = new java.awt.Insets(33, 0, 0, 0);
		mainPanel.add(botaoCarregarPrograma, gridBagConstraints);

		getContentPane().add(mainPanel);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void comboboxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboboxUsuarioActionPerformed
		SwingUtilities.invokeLater(new Runnable() {

			@Override
			public void run() {
				FrameInicialController controller = new FrameInicialController();
				if (comboboxUsuario.getSelectedIndex() != -1) {
					for (Curso curso : controller.getCursos((Usuario) comboboxUsuario.getSelectedItem())) {
						comboboxCurso.addItem(curso);
					}
					if (comboboxCurso.getItemCount() > 0) {
						comboboxCurso.setEnabled(true);
						botaoCarregarPrograma.setEnabled(true);
					}
				}
			}
		});
	}// GEN-LAST:event_comboboxUsuarioActionPerformed

	private void comboboxCursoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboboxCursoActionPerformed

	}// GEN-LAST:event_comboboxCursoActionPerformed

	private void botaoCarregarProgramaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoCarregarProgramaActionPerformed
		ModeloMainFrame frame = new ModeloMainFrame();
		frame.requestFocus();
		frame.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_botaoCarregarProgramaActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FrameInicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				FrameInicial frame = new FrameInicial();
				frame.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton botaoCarregarPrograma;
	private javax.swing.JComboBox<Curso> comboboxCurso;
	private javax.swing.JComboBox<Usuario> comboboxUsuario;
	private javax.swing.JLabel labelCurso;
	private javax.swing.JLabel labelTitulo;
	private javax.swing.JLabel labelUsuario;
	private javax.swing.JPanel mainPanel;
	// End of variables declaration//GEN-END:variables
}
