package view;

import javax.swing.JComboBox;

import controller.PanelInicialController;
import model.Curso;
import model.Usuario;

//@author savio
public class PanelInicial extends javax.swing.JPanel {

	private PanelInicialController controller;

	/**
	 * Creates new form PanelInicial
	 */
	public PanelInicial() {
		controller = new PanelInicialController(this);
		initComponents();
		Curso curso = this.controller.getCursos().get(0);
		Curso[] cursos = {curso,curso};
		this.comboboxCurso = new JComboBox<Curso>(cursos);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		comboboxUsuario = new javax.swing.JComboBox<>();
		comboboxUsuario.setBounds(51, 324, 190, 20);
		comboboxUsuario.setRenderer(new UsuarioCellRenderer());
		comboboxCurso = new javax.swing.JComboBox<>();
		comboboxCurso.setBounds(278, 324, 190, 20);
		labelUsuario = new javax.swing.JLabel();
		labelUsuario.setBounds(51, 304, 36, 14);
		labelCurso = new javax.swing.JLabel();
		labelCurso.setBounds(278, 304, 28, 14);
		botaoCarregarPrograma = new javax.swing.JButton();
		botaoCarregarPrograma.setBounds(597, 393, 61, 23);
		jLabel1 = new javax.swing.JLabel();
		jLabel1.setBounds(239, 64, 169, 60);

		setMinimumSize(new java.awt.Dimension(820, 570));

		comboboxUsuario.setModel(new ComboModel<Usuario>());
		comboboxUsuario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comboboxUsuarioActionPerformed(evt);
			}
		});

		comboboxCurso.setModel( new ComboModel<Curso>());
		comboboxCurso.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comboboxCursoActionPerformed(evt);
			}
		});

		labelUsuario.setText("Usuário");

		labelCurso.setText("Curso");

		botaoCarregarPrograma.setText("Iniciar");
		botaoCarregarPrograma.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoCarregarProgramaActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
		jLabel1.setText("Lacroix");
		setLayout(null);
		add(comboboxUsuario);
		add(labelUsuario);
		add(labelCurso);
		add(comboboxCurso);
		add(botaoCarregarPrograma);
		add(jLabel1);
	}// </editor-fold>

	private void comboboxCursoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void comboboxUsuarioActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void botaoCarregarProgramaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	// Variables declaration - do not modify
	private javax.swing.JButton botaoCarregarPrograma;
	private javax.swing.JComboBox<Curso> comboboxCurso;
	private javax.swing.JComboBox<Usuario> comboboxUsuario;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel labelCurso;
	private javax.swing.JLabel labelUsuario;
	// End of variables declaration
}
